// Code generated by protoc-gen-go. DO NOT EDIT.
// source: asset/assetside.proto

package asset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AssetSide struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string           `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string           `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Contract             string           `protobuf:"bytes,5,opt,name=contract,proto3" json:"contract,omitempty"`
	Base                 *DataBlockBase   `protobuf:"bytes,6,opt,name=base,proto3" json:"base,omitempty"`
	Picture              []*DocumentStore `protobuf:"bytes,7,rep,name=picture,proto3" json:"picture,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AssetSide) Reset()         { *m = AssetSide{} }
func (m *AssetSide) String() string { return proto.CompactTextString(m) }
func (*AssetSide) ProtoMessage()    {}
func (*AssetSide) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c84d66a87ee59d7, []int{0}
}

func (m *AssetSide) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetSide.Unmarshal(m, b)
}
func (m *AssetSide) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetSide.Marshal(b, m, deterministic)
}
func (m *AssetSide) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetSide.Merge(m, src)
}
func (m *AssetSide) XXX_Size() int {
	return xxx_messageInfo_AssetSide.Size(m)
}
func (m *AssetSide) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetSide.DiscardUnknown(m)
}

var xxx_messageInfo_AssetSide proto.InternalMessageInfo

func (m *AssetSide) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AssetSide) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AssetSide) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AssetSide) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AssetSide) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *AssetSide) GetBase() *DataBlockBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *AssetSide) GetPicture() []*DocumentStore {
	if m != nil {
		return m.Picture
	}
	return nil
}

// 数据入链请求结构
type RequestAssetsidePut struct {
	Key                  string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fun                  string     `protobuf:"bytes,2,opt,name=fun,proto3" json:"fun,omitempty"`
	Value                *AssetSide `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestAssetsidePut) Reset()         { *m = RequestAssetsidePut{} }
func (m *RequestAssetsidePut) String() string { return proto.CompactTextString(m) }
func (*RequestAssetsidePut) ProtoMessage()    {}
func (*RequestAssetsidePut) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c84d66a87ee59d7, []int{1}
}

func (m *RequestAssetsidePut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAssetsidePut.Unmarshal(m, b)
}
func (m *RequestAssetsidePut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAssetsidePut.Marshal(b, m, deterministic)
}
func (m *RequestAssetsidePut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAssetsidePut.Merge(m, src)
}
func (m *RequestAssetsidePut) XXX_Size() int {
	return xxx_messageInfo_RequestAssetsidePut.Size(m)
}
func (m *RequestAssetsidePut) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAssetsidePut.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAssetsidePut proto.InternalMessageInfo

func (m *RequestAssetsidePut) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RequestAssetsidePut) GetFun() string {
	if m != nil {
		return m.Fun
	}
	return ""
}

func (m *RequestAssetsidePut) GetValue() *AssetSide {
	if m != nil {
		return m.Value
	}
	return nil
}

type ResponseAssetside struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *AssetSide `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResponseAssetside) Reset()         { *m = ResponseAssetside{} }
func (m *ResponseAssetside) String() string { return proto.CompactTextString(m) }
func (*ResponseAssetside) ProtoMessage()    {}
func (*ResponseAssetside) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c84d66a87ee59d7, []int{2}
}

func (m *ResponseAssetside) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAssetside.Unmarshal(m, b)
}
func (m *ResponseAssetside) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAssetside.Marshal(b, m, deterministic)
}
func (m *ResponseAssetside) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAssetside.Merge(m, src)
}
func (m *ResponseAssetside) XXX_Size() int {
	return xxx_messageInfo_ResponseAssetside.Size(m)
}
func (m *ResponseAssetside) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAssetside.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAssetside proto.InternalMessageInfo

func (m *ResponseAssetside) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseAssetside) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseAssetside) GetData() *AssetSide {
	if m != nil {
		return m.Data
	}
	return nil
}

// 资产富查询请求结构
type RequestAssetsideRichQuery struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Rtype                int32    `protobuf:"varint,2,opt,name=rtype,proto3" json:"rtype,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAssetsideRichQuery) Reset()         { *m = RequestAssetsideRichQuery{} }
func (m *RequestAssetsideRichQuery) String() string { return proto.CompactTextString(m) }
func (*RequestAssetsideRichQuery) ProtoMessage()    {}
func (*RequestAssetsideRichQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c84d66a87ee59d7, []int{3}
}

func (m *RequestAssetsideRichQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAssetsideRichQuery.Unmarshal(m, b)
}
func (m *RequestAssetsideRichQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAssetsideRichQuery.Marshal(b, m, deterministic)
}
func (m *RequestAssetsideRichQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAssetsideRichQuery.Merge(m, src)
}
func (m *RequestAssetsideRichQuery) XXX_Size() int {
	return xxx_messageInfo_RequestAssetsideRichQuery.Size(m)
}
func (m *RequestAssetsideRichQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAssetsideRichQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAssetsideRichQuery proto.InternalMessageInfo

func (m *RequestAssetsideRichQuery) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RequestAssetsideRichQuery) GetRtype() int32 {
	if m != nil {
		return m.Rtype
	}
	return 0
}

func (m *RequestAssetsideRichQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*AssetSide)(nil), "asset.AssetSide")
	proto.RegisterType((*RequestAssetsidePut)(nil), "asset.RequestAssetsidePut")
	proto.RegisterType((*ResponseAssetside)(nil), "asset.ResponseAssetside")
	proto.RegisterType((*RequestAssetsideRichQuery)(nil), "asset.RequestAssetsideRichQuery")
}

func init() { proto.RegisterFile("asset/assetside.proto", fileDescriptor_1c84d66a87ee59d7) }

var fileDescriptor_1c84d66a87ee59d7 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x93, 0xb4, 0x76, 0x0a, 0x52, 0xd7, 0x0a, 0x6b, 0x4f, 0x25, 0x88, 0xf4, 0x14,
	0xa1, 0x3e, 0x41, 0x8b, 0x0f, 0xa0, 0xdb, 0x83, 0x47, 0x99, 0x26, 0x63, 0xbb, 0x34, 0xc9, 0xc6,
	0xec, 0x46, 0xe8, 0x63, 0xfa, 0x46, 0xb2, 0xbb, 0x49, 0x29, 0x82, 0x97, 0x65, 0xfe, 0x6f, 0x06,
	0xfe, 0x9d, 0x7f, 0xe0, 0x0e, 0xb5, 0x26, 0xf3, 0xe4, 0x5e, 0x2d, 0x73, 0x4a, 0xeb, 0x46, 0x19,
	0xc5, 0x62, 0x07, 0xe6, 0xfc, 0xa2, 0xfb, 0x51, 0x62, 0x85, 0xfb, 0x6e, 0x20, 0xf9, 0x09, 0x60,
	0xbc, 0xb6, 0x78, 0x2b, 0x73, 0x62, 0xd7, 0x30, 0x90, 0x39, 0x0f, 0x16, 0xc1, 0x72, 0x2c, 0x06,
	0x32, 0x67, 0x0c, 0xa2, 0x0a, 0x4b, 0xe2, 0x03, 0x47, 0x5c, 0xcd, 0x66, 0x10, 0xd7, 0x07, 0x55,
	0x11, 0x0f, 0x1d, 0xf4, 0xc2, 0x52, 0x2a, 0x51, 0x16, 0x3c, 0xf2, 0xd4, 0x09, 0x36, 0x87, 0xab,
	0x4c, 0x55, 0xa6, 0xc1, 0xcc, 0xf0, 0xd8, 0x35, 0xce, 0x9a, 0x2d, 0x21, 0xda, 0xa1, 0x26, 0x3e,
	0x5c, 0x04, 0xcb, 0xc9, 0x6a, 0x96, 0xba, 0xcf, 0xa5, 0x2f, 0x68, 0x70, 0x53, 0xa8, 0xec, 0xb8,
	0x41, 0x4d, 0xc2, 0x4d, 0xb0, 0x14, 0x46, 0xb5, 0xcc, 0x4c, 0xdb, 0x10, 0x1f, 0x2d, 0xc2, 0xcb,
	0x61, 0x95, 0xb5, 0x25, 0x55, 0x66, 0x6b, 0x54, 0x43, 0xa2, 0x1f, 0x4a, 0x10, 0x6e, 0x05, 0x7d,
	0xb5, 0xa4, 0xcd, 0xba, 0x8f, 0xe3, 0xb5, 0x35, 0x6c, 0x0a, 0xe1, 0x91, 0x4e, 0xdd, 0x76, 0xb6,
	0xb4, 0xe4, 0xb3, 0xad, 0xba, 0xed, 0x6c, 0xc9, 0x1e, 0x21, 0xfe, 0xc6, 0xa2, 0xf5, 0xcb, 0x4d,
	0x56, 0xd3, 0xce, 0xe8, 0x9c, 0x90, 0xf0, 0xed, 0x64, 0x0f, 0x37, 0x82, 0x74, 0xad, 0x2a, 0x4d,
	0x67, 0x0f, 0x9b, 0x56, 0xa6, 0x72, 0x72, 0x0e, 0xb1, 0x70, 0x35, 0xe3, 0x30, 0x2a, 0x49, 0x6b,
	0xdc, 0xf7, 0x21, 0xf6, 0x92, 0x3d, 0x40, 0x94, 0xa3, 0xc1, 0x7f, 0x9d, 0x5c, 0x37, 0x79, 0x87,
	0xfb, 0xbf, 0xbb, 0x08, 0x99, 0x1d, 0xde, 0x5a, 0x6a, 0x4e, 0x36, 0xf4, 0x42, 0x96, 0xd2, 0x74,
	0x8e, 0x5e, 0x58, 0xda, 0x98, 0x53, 0xed, 0x0d, 0x63, 0xe1, 0x45, 0x77, 0xda, 0xb0, 0x3f, 0xed,
	0x6e, 0xe8, 0xee, 0xff, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xbb, 0x06, 0x6e, 0x39, 0x02,
	0x00, 0x00,
}
