// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basic/house_property.proto

package basic

import (
	fmt "fmt"
	math "math"
	"protobuf/projects/go/protocol/asset"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 房产信息
type HouseProperty struct {
	Owner                string     `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32      `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Base                 *BaseHouse `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HouseProperty) Reset()         { *m = HouseProperty{} }
func (m *HouseProperty) String() string { return proto.CompactTextString(m) }
func (*HouseProperty) ProtoMessage()    {}
func (*HouseProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a16acca893fc272, []int{0}
}

func (m *HouseProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseProperty.Unmarshal(m, b)
}
func (m *HouseProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseProperty.Marshal(b, m, deterministic)
}
func (m *HouseProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseProperty.Merge(m, src)
}
func (m *HouseProperty) XXX_Size() int {
	return xxx_messageInfo_HouseProperty.Size(m)
}
func (m *HouseProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseProperty.DiscardUnknown(m)
}

var xxx_messageInfo_HouseProperty proto.InternalMessageInfo

func (m *HouseProperty) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *HouseProperty) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HouseProperty) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *HouseProperty) GetBase() *BaseHouse {
	if m != nil {
		return m.Base
	}
	return nil
}

// ------------------------------------------------------基本信息--------------------------------------------------------//
type BaseHouse struct {
	OwnerId              string                 `protobuf:"bytes,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	OwnerType            int32                  `protobuf:"varint,2,opt,name=ownerType,proto3" json:"ownerType,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Location             string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	EntireDesc           string                 `protobuf:"bytes,5,opt,name=entireDesc,proto3" json:"entireDesc,omitempty"`
	AssetType            int32                  `protobuf:"varint,6,opt,name=assetType,proto3" json:"assetType,omitempty"`
	Picture              []*asset.DocumentStore `protobuf:"bytes,7,rep,name=picture,proto3" json:"picture,omitempty"`
	Qualification        *asset.DocumentStore   `protobuf:"bytes,8,opt,name=qualification,proto3" json:"qualification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BaseHouse) Reset()         { *m = BaseHouse{} }
func (m *BaseHouse) String() string { return proto.CompactTextString(m) }
func (*BaseHouse) ProtoMessage()    {}
func (*BaseHouse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a16acca893fc272, []int{1}
}

func (m *BaseHouse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseHouse.Unmarshal(m, b)
}
func (m *BaseHouse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseHouse.Marshal(b, m, deterministic)
}
func (m *BaseHouse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseHouse.Merge(m, src)
}
func (m *BaseHouse) XXX_Size() int {
	return xxx_messageInfo_BaseHouse.Size(m)
}
func (m *BaseHouse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseHouse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseHouse proto.InternalMessageInfo

func (m *BaseHouse) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *BaseHouse) GetOwnerType() int32 {
	if m != nil {
		return m.OwnerType
	}
	return 0
}

func (m *BaseHouse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseHouse) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *BaseHouse) GetEntireDesc() string {
	if m != nil {
		return m.EntireDesc
	}
	return ""
}

func (m *BaseHouse) GetAssetType() int32 {
	if m != nil {
		return m.AssetType
	}
	return 0
}

func (m *BaseHouse) GetPicture() []*asset.DocumentStore {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *BaseHouse) GetQualification() *asset.DocumentStore {
	if m != nil {
		return m.Qualification
	}
	return nil
}

func init() {
	proto.RegisterType((*HouseProperty)(nil), "basic.HouseProperty")
	proto.RegisterType((*BaseHouse)(nil), "basic.BaseHouse")
}

func init() { proto.RegisterFile("basic/house_property.proto", fileDescriptor_3a16acca893fc272) }

var fileDescriptor_3a16acca893fc272 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0x6d, 0xb7, 0xed, 0x4e, 0xa9, 0xc8, 0xd0, 0x43, 0x28, 0x22, 0x4b, 0xf1, 0xb0,
	0xa7, 0x14, 0xea, 0xcd, 0xa3, 0xf4, 0xa0, 0x37, 0x89, 0xde, 0x4b, 0xba, 0x1d, 0x35, 0xd0, 0x26,
	0x6b, 0x92, 0x45, 0xfa, 0x63, 0xfc, 0xaf, 0xb2, 0xb3, 0x6d, 0x55, 0xf0, 0x12, 0x66, 0xde, 0x9b,
	0xc7, 0x37, 0x4c, 0x60, 0xb6, 0xd1, 0xc1, 0x54, 0x8b, 0x77, 0xd7, 0x04, 0x5a, 0xd7, 0xde, 0xd5,
	0xe4, 0xe3, 0x41, 0xd6, 0xde, 0x45, 0x87, 0x19, 0x7b, 0x33, 0xa1, 0x43, 0xa0, 0xb8, 0xe0, 0x77,
	0xbd, 0xd7, 0x56, 0xbf, 0x51, 0x37, 0x30, 0x77, 0x30, 0x79, 0x68, 0x83, 0x4f, 0xc7, 0x1c, 0x4e,
	0x21, 0x73, 0x9f, 0x96, 0xbc, 0x48, 0x8a, 0xa4, 0xcc, 0x55, 0xd7, 0xe0, 0x05, 0xa4, 0x66, 0x2b,
	0x52, 0x96, 0x52, 0xb3, 0x45, 0x84, 0x7e, 0x3c, 0xd4, 0x24, 0x7a, 0x45, 0x52, 0x66, 0x8a, 0x6b,
	0xbc, 0x81, 0xfe, 0x46, 0x07, 0x12, 0xfd, 0x22, 0x29, 0xc7, 0xcb, 0x4b, 0xc9, 0x68, 0x79, 0xaf,
	0x03, 0x31, 0x41, 0xb1, 0x3b, 0xff, 0x4a, 0x21, 0x3f, 0x6b, 0x28, 0x60, 0xc8, 0x80, 0xc7, 0xed,
	0x91, 0x77, 0x6a, 0xf1, 0x0a, 0x72, 0x2e, 0x5f, 0x5a, 0x4c, 0xca, 0x98, 0x1f, 0xa1, 0xe5, 0x5b,
	0xbd, 0xef, 0xf8, 0xb9, 0xe2, 0x1a, 0x67, 0x30, 0xda, 0xb9, 0x4a, 0x47, 0xe3, 0x2c, 0xef, 0x90,
	0xab, 0x73, 0x8f, 0xd7, 0x00, 0x64, 0xa3, 0xf1, 0xb4, 0xa2, 0x50, 0x89, 0x8c, 0xdd, 0x5f, 0x4a,
	0x4b, 0xe3, 0xe3, 0x30, 0x6d, 0xd0, 0xd1, 0xce, 0x02, 0x4a, 0x18, 0xd6, 0xa6, 0x8a, 0x8d, 0x27,
	0x31, 0x2c, 0x7a, 0xe5, 0x78, 0x39, 0x95, 0x6c, 0xca, 0x95, 0xab, 0x9a, 0x3d, 0xd9, 0xf8, 0x1c,
	0x9d, 0x27, 0x75, 0x1a, 0xc2, 0x3b, 0x98, 0x7c, 0x34, 0x7a, 0x67, 0x5e, 0xcd, 0x71, 0x9d, 0x11,
	0x9f, 0xe4, 0xff, 0xd4, 0xdf, 0xd1, 0xcd, 0x80, 0xff, 0xe5, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0xb8, 0x05, 0xd7, 0xd6, 0x01, 0x00, 0x00,
}
