// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basic/natural_person.proto

package basic

import (
	fmt "fmt"
	math "math"
	"protobuf/projects/go/protocol/asset"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 自然人对象
type NaturalPerson struct {
	Owner                string          `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id                   string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32           `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Base                 *BaseNatural    `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	Financial            *Financial      `protobuf:"bytes,5,opt,name=financial,proto3" json:"financial,omitempty"`
	Preference           *Preference     `protobuf:"bytes,6,opt,name=preference,proto3" json:"preference,omitempty"`
	Social               *SocialRelation `protobuf:"bytes,7,opt,name=social,proto3" json:"social,omitempty"`
	Credit               *Credit         `protobuf:"bytes,8,opt,name=credit,proto3" json:"credit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NaturalPerson) Reset()         { *m = NaturalPerson{} }
func (m *NaturalPerson) String() string { return proto.CompactTextString(m) }
func (*NaturalPerson) ProtoMessage()    {}
func (*NaturalPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{0}
}

func (m *NaturalPerson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NaturalPerson.Unmarshal(m, b)
}
func (m *NaturalPerson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NaturalPerson.Marshal(b, m, deterministic)
}
func (m *NaturalPerson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NaturalPerson.Merge(m, src)
}
func (m *NaturalPerson) XXX_Size() int {
	return xxx_messageInfo_NaturalPerson.Size(m)
}
func (m *NaturalPerson) XXX_DiscardUnknown() {
	xxx_messageInfo_NaturalPerson.DiscardUnknown(m)
}

var xxx_messageInfo_NaturalPerson proto.InternalMessageInfo

func (m *NaturalPerson) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NaturalPerson) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NaturalPerson) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NaturalPerson) GetBase() *BaseNatural {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *NaturalPerson) GetFinancial() *Financial {
	if m != nil {
		return m.Financial
	}
	return nil
}

func (m *NaturalPerson) GetPreference() *Preference {
	if m != nil {
		return m.Preference
	}
	return nil
}

func (m *NaturalPerson) GetSocial() *SocialRelation {
	if m != nil {
		return m.Social
	}
	return nil
}

func (m *NaturalPerson) GetCredit() *Credit {
	if m != nil {
		return m.Credit
	}
	return nil
}

// ----------------------------------------------------------基本信息-----------------------------------------------------//
type BaseNatural struct {
	Position             *Position     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Occupation           []*Occupation `protobuf:"bytes,2,rep,name=occupation,proto3" json:"occupation,omitempty"`
	Education            []*Education  `protobuf:"bytes,3,rep,name=education,proto3" json:"education,omitempty"`
	PersonalInfo         *Personal     `protobuf:"bytes,4,opt,name=personalInfo,proto3" json:"personalInfo,omitempty"`
	ContactInfo          *Contact      `protobuf:"bytes,5,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BaseNatural) Reset()         { *m = BaseNatural{} }
func (m *BaseNatural) String() string { return proto.CompactTextString(m) }
func (*BaseNatural) ProtoMessage()    {}
func (*BaseNatural) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{1}
}

func (m *BaseNatural) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseNatural.Unmarshal(m, b)
}
func (m *BaseNatural) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseNatural.Marshal(b, m, deterministic)
}
func (m *BaseNatural) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseNatural.Merge(m, src)
}
func (m *BaseNatural) XXX_Size() int {
	return xxx_messageInfo_BaseNatural.Size(m)
}
func (m *BaseNatural) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseNatural.DiscardUnknown(m)
}

var xxx_messageInfo_BaseNatural proto.InternalMessageInfo

func (m *BaseNatural) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *BaseNatural) GetOccupation() []*Occupation {
	if m != nil {
		return m.Occupation
	}
	return nil
}

func (m *BaseNatural) GetEducation() []*Education {
	if m != nil {
		return m.Education
	}
	return nil
}

func (m *BaseNatural) GetPersonalInfo() *Personal {
	if m != nil {
		return m.PersonalInfo
	}
	return nil
}

func (m *BaseNatural) GetContactInfo() *Contact {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

// 位置信息
type Position struct {
	Nationality          string   `protobuf:"bytes,1,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Birthplace           string   `protobuf:"bytes,2,opt,name=birthplace,proto3" json:"birthplace,omitempty"`
	Residence            string   `protobuf:"bytes,3,opt,name=residence,proto3" json:"residence,omitempty"`
	AncestralHome        string   `protobuf:"bytes,4,opt,name=ancestralHome,proto3" json:"ancestralHome,omitempty"`
	Domicile             string   `protobuf:"bytes,5,opt,name=domicile,proto3" json:"domicile,omitempty"`
	Postcode             string   `protobuf:"bytes,6,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Workplace            string   `protobuf:"bytes,7,opt,name=workplace,proto3" json:"workplace,omitempty"`
	CountryCode          string   `protobuf:"bytes,8,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	County               string   `protobuf:"bytes,9,opt,name=county,proto3" json:"county,omitempty"`
	State                string   `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	City                 string   `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	Other                string   `protobuf:"bytes,12,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{2}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetNationality() string {
	if m != nil {
		return m.Nationality
	}
	return ""
}

func (m *Position) GetBirthplace() string {
	if m != nil {
		return m.Birthplace
	}
	return ""
}

func (m *Position) GetResidence() string {
	if m != nil {
		return m.Residence
	}
	return ""
}

func (m *Position) GetAncestralHome() string {
	if m != nil {
		return m.AncestralHome
	}
	return ""
}

func (m *Position) GetDomicile() string {
	if m != nil {
		return m.Domicile
	}
	return ""
}

func (m *Position) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *Position) GetWorkplace() string {
	if m != nil {
		return m.Workplace
	}
	return ""
}

func (m *Position) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Position) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *Position) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Position) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Position) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

// 职业信息
type Occupation struct {
	Start                string   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Duty                 string   `protobuf:"bytes,3,opt,name=duty,proto3" json:"duty,omitempty"`
	Salary               string   `protobuf:"bytes,4,opt,name=salary,proto3" json:"salary,omitempty"`
	Feats                string   `protobuf:"bytes,5,opt,name=feats,proto3" json:"feats,omitempty"`
	Whyleave             string   `protobuf:"bytes,6,opt,name=whyleave,proto3" json:"whyleave,omitempty"`
	Other                string   `protobuf:"bytes,7,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Occupation) Reset()         { *m = Occupation{} }
func (m *Occupation) String() string { return proto.CompactTextString(m) }
func (*Occupation) ProtoMessage()    {}
func (*Occupation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{3}
}

func (m *Occupation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Occupation.Unmarshal(m, b)
}
func (m *Occupation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Occupation.Marshal(b, m, deterministic)
}
func (m *Occupation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Occupation.Merge(m, src)
}
func (m *Occupation) XXX_Size() int {
	return xxx_messageInfo_Occupation.Size(m)
}
func (m *Occupation) XXX_DiscardUnknown() {
	xxx_messageInfo_Occupation.DiscardUnknown(m)
}

var xxx_messageInfo_Occupation proto.InternalMessageInfo

func (m *Occupation) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *Occupation) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *Occupation) GetDuty() string {
	if m != nil {
		return m.Duty
	}
	return ""
}

func (m *Occupation) GetSalary() string {
	if m != nil {
		return m.Salary
	}
	return ""
}

func (m *Occupation) GetFeats() string {
	if m != nil {
		return m.Feats
	}
	return ""
}

func (m *Occupation) GetWhyleave() string {
	if m != nil {
		return m.Whyleave
	}
	return ""
}

func (m *Occupation) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

// 教育信息
type Education struct {
	Start                string   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Degree               string   `protobuf:"bytes,3,opt,name=degree,proto3" json:"degree,omitempty"`
	Awards               string   `protobuf:"bytes,4,opt,name=awards,proto3" json:"awards,omitempty"`
	Other                string   `protobuf:"bytes,5,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Education) Reset()         { *m = Education{} }
func (m *Education) String() string { return proto.CompactTextString(m) }
func (*Education) ProtoMessage()    {}
func (*Education) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{4}
}

func (m *Education) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Education.Unmarshal(m, b)
}
func (m *Education) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Education.Marshal(b, m, deterministic)
}
func (m *Education) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Education.Merge(m, src)
}
func (m *Education) XXX_Size() int {
	return xxx_messageInfo_Education.Size(m)
}
func (m *Education) XXX_DiscardUnknown() {
	xxx_messageInfo_Education.DiscardUnknown(m)
}

var xxx_messageInfo_Education proto.InternalMessageInfo

func (m *Education) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *Education) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *Education) GetDegree() string {
	if m != nil {
		return m.Degree
	}
	return ""
}

func (m *Education) GetAwards() string {
	if m != nil {
		return m.Awards
	}
	return ""
}

func (m *Education) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

// 个人信息
type Personal struct {
	Name                  string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender                string               `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday              string               `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Nickname              string               `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ID_Number             string               `protobuf:"bytes,5,opt,name=ID_Number,json=IDNumber,proto3" json:"ID_Number,omitempty"`
	ID_Card_Front         *asset.DocumentStore `protobuf:"bytes,6,opt,name=ID_Card_Front,json=IDCardFront,proto3" json:"ID_Card_Front,omitempty"`
	ID_Card_Back          *asset.DocumentStore `protobuf:"bytes,7,opt,name=ID_Card_Back,json=IDCardBack,proto3" json:"ID_Card_Back,omitempty"`
	ID_Card_Hold          *asset.DocumentStore `protobuf:"bytes,8,opt,name=ID_Card_Hold,json=IDCardHold,proto3" json:"ID_Card_Hold,omitempty"`
	PassFront             *asset.DocumentStore `protobuf:"bytes,9,opt,name=passFront,proto3" json:"passFront,omitempty"`
	PassContent           *asset.DocumentStore `protobuf:"bytes,10,opt,name=passContent,proto3" json:"passContent,omitempty"`
	PassHold              *asset.DocumentStore `protobuf:"bytes,11,opt,name=passHold,proto3" json:"passHold,omitempty"`
	DrivingLicenseFront   *asset.DocumentStore `protobuf:"bytes,12,opt,name=drivingLicenseFront,proto3" json:"drivingLicenseFront,omitempty"`
	DrivingLicenseContent *asset.DocumentStore `protobuf:"bytes,13,opt,name=drivingLicenseContent,proto3" json:"drivingLicenseContent,omitempty"`
	DrivingLicenseHold    *asset.DocumentStore `protobuf:"bytes,14,opt,name=drivingLicenseHold,proto3" json:"drivingLicenseHold,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *Personal) Reset()         { *m = Personal{} }
func (m *Personal) String() string { return proto.CompactTextString(m) }
func (*Personal) ProtoMessage()    {}
func (*Personal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{5}
}

func (m *Personal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Personal.Unmarshal(m, b)
}
func (m *Personal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Personal.Marshal(b, m, deterministic)
}
func (m *Personal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Personal.Merge(m, src)
}
func (m *Personal) XXX_Size() int {
	return xxx_messageInfo_Personal.Size(m)
}
func (m *Personal) XXX_DiscardUnknown() {
	xxx_messageInfo_Personal.DiscardUnknown(m)
}

var xxx_messageInfo_Personal proto.InternalMessageInfo

func (m *Personal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Personal) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Personal) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Personal) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Personal) GetID_Number() string {
	if m != nil {
		return m.ID_Number
	}
	return ""
}

func (m *Personal) GetID_Card_Front() *asset.DocumentStore {
	if m != nil {
		return m.ID_Card_Front
	}
	return nil
}

func (m *Personal) GetID_Card_Back() *asset.DocumentStore {
	if m != nil {
		return m.ID_Card_Back
	}
	return nil
}

func (m *Personal) GetID_Card_Hold() *asset.DocumentStore {
	if m != nil {
		return m.ID_Card_Hold
	}
	return nil
}

func (m *Personal) GetPassFront() *asset.DocumentStore {
	if m != nil {
		return m.PassFront
	}
	return nil
}

func (m *Personal) GetPassContent() *asset.DocumentStore {
	if m != nil {
		return m.PassContent
	}
	return nil
}

func (m *Personal) GetPassHold() *asset.DocumentStore {
	if m != nil {
		return m.PassHold
	}
	return nil
}

func (m *Personal) GetDrivingLicenseFront() *asset.DocumentStore {
	if m != nil {
		return m.DrivingLicenseFront
	}
	return nil
}

func (m *Personal) GetDrivingLicenseContent() *asset.DocumentStore {
	if m != nil {
		return m.DrivingLicenseContent
	}
	return nil
}

func (m *Personal) GetDrivingLicenseHold() *asset.DocumentStore {
	if m != nil {
		return m.DrivingLicenseHold
	}
	return nil
}

// 联络信息
type Contact struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Mail                 string   `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail,omitempty"`
	Wechat               string   `protobuf:"bytes,3,opt,name=wechat,proto3" json:"wechat,omitempty"`
	QQ                   string   `protobuf:"bytes,4,opt,name=QQ,proto3" json:"QQ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{6}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Contact) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *Contact) GetWechat() string {
	if m != nil {
		return m.Wechat
	}
	return ""
}

func (m *Contact) GetQQ() string {
	if m != nil {
		return m.QQ
	}
	return ""
}

// ---------------------------------------------------------财务信息-----------------------------------------------------//
type Financial struct {
	LegalTender          *LegalTender    `protobuf:"bytes,1,opt,name=legalTender,proto3" json:"legalTender,omitempty"`
	CryptoCurrency       *CryptoCurrency `protobuf:"bytes,2,opt,name=cryptoCurrency,proto3" json:"cryptoCurrency,omitempty"`
	AssetManage          *Asset          `protobuf:"bytes,3,opt,name=assetManage,proto3" json:"assetManage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Financial) Reset()         { *m = Financial{} }
func (m *Financial) String() string { return proto.CompactTextString(m) }
func (*Financial) ProtoMessage()    {}
func (*Financial) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{7}
}

func (m *Financial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Financial.Unmarshal(m, b)
}
func (m *Financial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Financial.Marshal(b, m, deterministic)
}
func (m *Financial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Financial.Merge(m, src)
}
func (m *Financial) XXX_Size() int {
	return xxx_messageInfo_Financial.Size(m)
}
func (m *Financial) XXX_DiscardUnknown() {
	xxx_messageInfo_Financial.DiscardUnknown(m)
}

var xxx_messageInfo_Financial proto.InternalMessageInfo

func (m *Financial) GetLegalTender() *LegalTender {
	if m != nil {
		return m.LegalTender
	}
	return nil
}

func (m *Financial) GetCryptoCurrency() *CryptoCurrency {
	if m != nil {
		return m.CryptoCurrency
	}
	return nil
}

func (m *Financial) GetAssetManage() *Asset {
	if m != nil {
		return m.AssetManage
	}
	return nil
}

// 法币财务信息
type LegalTender struct {
	AnnualIncome         int64    `protobuf:"varint,1,opt,name=annualIncome,proto3" json:"annualIncome,omitempty"`
	AnnualConsume        int64    `protobuf:"varint,2,opt,name=annualConsume,proto3" json:"annualConsume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LegalTender) Reset()         { *m = LegalTender{} }
func (m *LegalTender) String() string { return proto.CompactTextString(m) }
func (*LegalTender) ProtoMessage()    {}
func (*LegalTender) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{8}
}

func (m *LegalTender) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LegalTender.Unmarshal(m, b)
}
func (m *LegalTender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LegalTender.Marshal(b, m, deterministic)
}
func (m *LegalTender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LegalTender.Merge(m, src)
}
func (m *LegalTender) XXX_Size() int {
	return xxx_messageInfo_LegalTender.Size(m)
}
func (m *LegalTender) XXX_DiscardUnknown() {
	xxx_messageInfo_LegalTender.DiscardUnknown(m)
}

var xxx_messageInfo_LegalTender proto.InternalMessageInfo

func (m *LegalTender) GetAnnualIncome() int64 {
	if m != nil {
		return m.AnnualIncome
	}
	return 0
}

func (m *LegalTender) GetAnnualConsume() int64 {
	if m != nil {
		return m.AnnualConsume
	}
	return 0
}

// 代币财务信息
type CryptoCurrency struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CryptoCurrency) Reset()         { *m = CryptoCurrency{} }
func (m *CryptoCurrency) String() string { return proto.CompactTextString(m) }
func (*CryptoCurrency) ProtoMessage()    {}
func (*CryptoCurrency) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{9}
}

func (m *CryptoCurrency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoCurrency.Unmarshal(m, b)
}
func (m *CryptoCurrency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoCurrency.Marshal(b, m, deterministic)
}
func (m *CryptoCurrency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoCurrency.Merge(m, src)
}
func (m *CryptoCurrency) XXX_Size() int {
	return xxx_messageInfo_CryptoCurrency.Size(m)
}
func (m *CryptoCurrency) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoCurrency.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoCurrency proto.InternalMessageInfo

// 固定资产(暂不展开)
type Asset struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{10}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

// --------------------------------------------------------行为偏好-------------------------------------------------------//
type Preference struct {
	Interests            []*Interests          `protobuf:"bytes,1,rep,name=Interests,proto3" json:"Interests,omitempty"`
	ConsumerPreference   []*ConsumerPreference `protobuf:"bytes,2,rep,name=consumerPreference,proto3" json:"consumerPreference,omitempty"`
	SpendTime            []*SpendTime          `protobuf:"bytes,3,rep,name=spendTime,proto3" json:"spendTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Preference) Reset()         { *m = Preference{} }
func (m *Preference) String() string { return proto.CompactTextString(m) }
func (*Preference) ProtoMessage()    {}
func (*Preference) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{11}
}

func (m *Preference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preference.Unmarshal(m, b)
}
func (m *Preference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preference.Marshal(b, m, deterministic)
}
func (m *Preference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preference.Merge(m, src)
}
func (m *Preference) XXX_Size() int {
	return xxx_messageInfo_Preference.Size(m)
}
func (m *Preference) XXX_DiscardUnknown() {
	xxx_messageInfo_Preference.DiscardUnknown(m)
}

var xxx_messageInfo_Preference proto.InternalMessageInfo

func (m *Preference) GetInterests() []*Interests {
	if m != nil {
		return m.Interests
	}
	return nil
}

func (m *Preference) GetConsumerPreference() []*ConsumerPreference {
	if m != nil {
		return m.ConsumerPreference
	}
	return nil
}

func (m *Preference) GetSpendTime() []*SpendTime {
	if m != nil {
		return m.SpendTime
	}
	return nil
}

// 兴趣爱好
type Interests struct {
	Hobby                string   `protobuf:"bytes,1,opt,name=hobby,proto3" json:"hobby,omitempty"`
	Score                string   `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Interests) Reset()         { *m = Interests{} }
func (m *Interests) String() string { return proto.CompactTextString(m) }
func (*Interests) ProtoMessage()    {}
func (*Interests) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{12}
}

func (m *Interests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interests.Unmarshal(m, b)
}
func (m *Interests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interests.Marshal(b, m, deterministic)
}
func (m *Interests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interests.Merge(m, src)
}
func (m *Interests) XXX_Size() int {
	return xxx_messageInfo_Interests.Size(m)
}
func (m *Interests) XXX_DiscardUnknown() {
	xxx_messageInfo_Interests.DiscardUnknown(m)
}

var xxx_messageInfo_Interests proto.InternalMessageInfo

func (m *Interests) GetHobby() string {
	if m != nil {
		return m.Hobby
	}
	return ""
}

func (m *Interests) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

// 消费偏好(暂不展开)
type ConsumerPreference struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumerPreference) Reset()         { *m = ConsumerPreference{} }
func (m *ConsumerPreference) String() string { return proto.CompactTextString(m) }
func (*ConsumerPreference) ProtoMessage()    {}
func (*ConsumerPreference) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{13}
}

func (m *ConsumerPreference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerPreference.Unmarshal(m, b)
}
func (m *ConsumerPreference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerPreference.Marshal(b, m, deterministic)
}
func (m *ConsumerPreference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerPreference.Merge(m, src)
}
func (m *ConsumerPreference) XXX_Size() int {
	return xxx_messageInfo_ConsumerPreference.Size(m)
}
func (m *ConsumerPreference) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerPreference.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerPreference proto.InternalMessageInfo

// 时间投入(暂不展开)
type SpendTime struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpendTime) Reset()         { *m = SpendTime{} }
func (m *SpendTime) String() string { return proto.CompactTextString(m) }
func (*SpendTime) ProtoMessage()    {}
func (*SpendTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{14}
}

func (m *SpendTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpendTime.Unmarshal(m, b)
}
func (m *SpendTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpendTime.Marshal(b, m, deterministic)
}
func (m *SpendTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendTime.Merge(m, src)
}
func (m *SpendTime) XXX_Size() int {
	return xxx_messageInfo_SpendTime.Size(m)
}
func (m *SpendTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendTime.DiscardUnknown(m)
}

var xxx_messageInfo_SpendTime proto.InternalMessageInfo

// -------------------------------------------------------社交关系--------------------------------------------------------//
type SocialRelation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialRelation) Reset()         { *m = SocialRelation{} }
func (m *SocialRelation) String() string { return proto.CompactTextString(m) }
func (*SocialRelation) ProtoMessage()    {}
func (*SocialRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{15}
}

func (m *SocialRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialRelation.Unmarshal(m, b)
}
func (m *SocialRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialRelation.Marshal(b, m, deterministic)
}
func (m *SocialRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialRelation.Merge(m, src)
}
func (m *SocialRelation) XXX_Size() int {
	return xxx_messageInfo_SocialRelation.Size(m)
}
func (m *SocialRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialRelation.DiscardUnknown(m)
}

var xxx_messageInfo_SocialRelation proto.InternalMessageInfo

// ------------------------------------------------------征信---------------------------------------------------------//
type Credit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credit) Reset()         { *m = Credit{} }
func (m *Credit) String() string { return proto.CompactTextString(m) }
func (*Credit) ProtoMessage()    {}
func (*Credit) Descriptor() ([]byte, []int) {
	return fileDescriptor_a15aca9d92f0028e, []int{16}
}

func (m *Credit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credit.Unmarshal(m, b)
}
func (m *Credit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credit.Marshal(b, m, deterministic)
}
func (m *Credit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credit.Merge(m, src)
}
func (m *Credit) XXX_Size() int {
	return xxx_messageInfo_Credit.Size(m)
}
func (m *Credit) XXX_DiscardUnknown() {
	xxx_messageInfo_Credit.DiscardUnknown(m)
}

var xxx_messageInfo_Credit proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NaturalPerson)(nil), "basic.NaturalPerson")
	proto.RegisterType((*BaseNatural)(nil), "basic.BaseNatural")
	proto.RegisterType((*Position)(nil), "basic.Position")
	proto.RegisterType((*Occupation)(nil), "basic.Occupation")
	proto.RegisterType((*Education)(nil), "basic.Education")
	proto.RegisterType((*Personal)(nil), "basic.Personal")
	proto.RegisterType((*Contact)(nil), "basic.Contact")
	proto.RegisterType((*Financial)(nil), "basic.Financial")
	proto.RegisterType((*LegalTender)(nil), "basic.LegalTender")
	proto.RegisterType((*CryptoCurrency)(nil), "basic.CryptoCurrency")
	proto.RegisterType((*Asset)(nil), "basic.Asset")
	proto.RegisterType((*Preference)(nil), "basic.Preference")
	proto.RegisterType((*Interests)(nil), "basic.Interests")
	proto.RegisterType((*ConsumerPreference)(nil), "basic.ConsumerPreference")
	proto.RegisterType((*SpendTime)(nil), "basic.SpendTime")
	proto.RegisterType((*SocialRelation)(nil), "basic.SocialRelation")
	proto.RegisterType((*Credit)(nil), "basic.Credit")
}

func init() { proto.RegisterFile("basic/natural_person.proto", fileDescriptor_a15aca9d92f0028e) }

var fileDescriptor_a15aca9d92f0028e = []byte{
	// 1088 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x5d, 0x6f, 0x23, 0x35,
	0x17, 0x56, 0x92, 0x4d, 0x9a, 0x39, 0x93, 0xf6, 0xdd, 0xd7, 0x74, 0x57, 0x43, 0x41, 0xa8, 0x1a,
	0x01, 0xaa, 0x84, 0xc8, 0x2e, 0x5d, 0xb4, 0x70, 0xc3, 0x05, 0x9b, 0x50, 0x6d, 0xd0, 0xb2, 0x6c,
	0xdd, 0x95, 0xb8, 0xe0, 0xa2, 0x72, 0x3c, 0x6e, 0x33, 0xea, 0xc4, 0x1e, 0xd9, 0xce, 0x56, 0xb9,
	0xe7, 0xc7, 0x20, 0x24, 0x24, 0xee, 0xf8, 0x3b, 0xfc, 0x14, 0xe4, 0x63, 0xcf, 0x57, 0x29, 0x11,
	0x37, 0x23, 0x3f, 0xe7, 0x3c, 0xc7, 0xe7, 0x63, 0x8e, 0x7d, 0x0c, 0x47, 0x4b, 0x66, 0x72, 0xfe,
	0x44, 0x32, 0xbb, 0xd1, 0xac, 0xb8, 0x2c, 0x85, 0x36, 0x4a, 0x4e, 0x4b, 0xad, 0xac, 0x22, 0x43,
	0xd4, 0x1d, 0x25, 0xcc, 0x18, 0x61, 0x9f, 0xe0, 0xf7, 0x72, 0xcd, 0x24, 0xbb, 0x16, 0x9e, 0x90,
	0xfe, 0xd6, 0x87, 0xfd, 0xd7, 0xde, 0xf2, 0x0d, 0x1a, 0x92, 0x43, 0x18, 0xaa, 0x5b, 0x29, 0x74,
	0xd2, 0x3b, 0xee, 0x9d, 0x44, 0xd4, 0x03, 0x72, 0x00, 0xfd, 0x3c, 0x4b, 0xfa, 0x28, 0xea, 0xe7,
	0x19, 0x21, 0xf0, 0xc0, 0x6e, 0x4b, 0x91, 0x0c, 0x8e, 0x7b, 0x27, 0x43, 0x8a, 0x6b, 0xf2, 0x29,
	0x3c, 0x58, 0x32, 0x23, 0x92, 0x07, 0xc7, 0xbd, 0x93, 0xf8, 0x94, 0x4c, 0xd1, 0xf7, 0xf4, 0x05,
	0x33, 0x22, 0x78, 0xa0, 0xa8, 0x27, 0x53, 0x88, 0xae, 0x72, 0xc9, 0x24, 0xcf, 0x59, 0x91, 0x0c,
	0x91, 0xfc, 0x30, 0x90, 0xcf, 0x2a, 0x39, 0x6d, 0x28, 0xe4, 0x0b, 0x80, 0x52, 0x8b, 0x2b, 0xa1,
	0x85, 0xe4, 0x22, 0x19, 0xa1, 0xc1, 0xff, 0x83, 0xc1, 0x9b, 0x5a, 0x41, 0x5b, 0x24, 0xf2, 0x39,
	0x8c, 0x8c, 0xc2, 0xfd, 0xf7, 0x90, 0xfe, 0x28, 0xd0, 0x2f, 0x50, 0x48, 0x45, 0xc1, 0x6c, 0xae,
	0x24, 0x0d, 0x24, 0xf2, 0x09, 0x8c, 0xb8, 0x16, 0x59, 0x6e, 0x93, 0x31, 0xd2, 0xf7, 0x03, 0x7d,
	0x86, 0x42, 0x1a, 0x94, 0xe9, 0x2f, 0x7d, 0x88, 0x5b, 0xe9, 0x90, 0xcf, 0x60, 0x5c, 0x2a, 0x93,
	0xbb, 0xad, 0xb0, 0x5a, 0xf1, 0xe9, 0xff, 0xaa, 0xb0, 0x82, 0x98, 0xd6, 0x04, 0x97, 0x85, 0xe2,
	0x7c, 0x53, 0xa2, 0xe7, 0xa4, 0x7f, 0x3c, 0x68, 0x65, 0xf1, 0x63, 0xad, 0xa0, 0x2d, 0x92, 0x2b,
	0x94, 0xc8, 0x36, 0xdc, 0x5b, 0x0c, 0xd0, 0xa2, 0x2a, 0xd4, 0x77, 0x95, 0x9c, 0x36, 0x14, 0xf2,
	0x0c, 0x26, 0xfe, 0xef, 0xb3, 0x62, 0x21, 0xaf, 0x54, 0xf8, 0x11, 0x75, 0x4c, 0x41, 0x45, 0x3b,
	0x24, 0xf2, 0x14, 0x62, 0xae, 0xa4, 0x65, 0xdc, 0xa2, 0x8d, 0xff, 0x1f, 0x07, 0x55, 0x01, 0xbc,
	0x86, 0xb6, 0x29, 0xe9, 0x5f, 0x7d, 0x18, 0x57, 0x09, 0x92, 0x63, 0x88, 0x25, 0x7a, 0x67, 0x45,
	0x6e, 0xb7, 0xa1, 0x69, 0xda, 0x22, 0xf2, 0x11, 0xc0, 0x32, 0xd7, 0x76, 0x55, 0x16, 0x8c, 0x8b,
	0xd0, 0x42, 0x2d, 0x09, 0xf9, 0x10, 0x22, 0x2d, 0x4c, 0x9e, 0xe1, 0xdf, 0x1d, 0xa0, 0xba, 0x11,
	0x90, 0x8f, 0x61, 0x9f, 0x49, 0x2e, 0x8c, 0xd5, 0xac, 0x78, 0xa9, 0xd6, 0xbe, 0xbb, 0x22, 0xda,
	0x15, 0x92, 0x23, 0x18, 0x67, 0x6a, 0x9d, 0xf3, 0xbc, 0x10, 0x98, 0x41, 0x44, 0x6b, 0xec, 0x74,
	0xa5, 0x32, 0x96, 0xab, 0xcc, 0x37, 0x4f, 0x44, 0x6b, 0xec, 0x7c, 0xdf, 0x2a, 0x7d, 0xe3, 0x43,
	0xdb, 0xf3, 0xbe, 0x6b, 0x81, 0xcb, 0x8d, 0xab, 0x8d, 0xb4, 0x7a, 0x3b, 0x73, 0xc6, 0x63, 0x9f,
	0x5b, 0x4b, 0x44, 0x1e, 0xc3, 0x08, 0xe1, 0x36, 0x89, 0x50, 0x19, 0x90, 0x3b, 0x44, 0xc6, 0x32,
	0x2b, 0x12, 0xf0, 0x87, 0x08, 0x81, 0x3b, 0x34, 0xdc, 0x15, 0x29, 0x46, 0x21, 0xae, 0xf1, 0xb8,
	0xd9, 0x95, 0xd0, 0xc9, 0x24, 0x1c, 0x37, 0x07, 0xd2, 0x5f, 0x7b, 0x00, 0x4d, 0x53, 0x84, 0xed,
	0xb4, 0xad, 0xce, 0x24, 0x02, 0xf2, 0x10, 0x06, 0x42, 0x56, 0x87, 0xd2, 0x2d, 0x9d, 0x83, 0x6c,
	0x63, 0xb7, 0xa1, 0x8a, 0xb8, 0x76, 0x21, 0x1a, 0x56, 0x30, 0xbd, 0x0d, 0x95, 0x0b, 0xc8, 0xed,
	0x79, 0x25, 0x98, 0x35, 0xa1, 0x5e, 0x1e, 0xb8, 0x62, 0xdd, 0xae, 0xb6, 0x85, 0x60, 0xef, 0xea,
	0x62, 0x55, 0xb8, 0x09, 0x75, 0xaf, 0x1d, 0xea, 0x16, 0xa2, 0xba, 0x19, 0xff, 0x73, 0xa0, 0x8f,
	0x61, 0x94, 0x89, 0x6b, 0x2d, 0xaa, 0x1f, 0x1e, 0x90, 0x93, 0xb3, 0x5b, 0xa6, 0x33, 0x53, 0x05,
	0xeb, 0x51, 0xe3, 0x7a, 0xd8, 0x76, 0xfd, 0xfb, 0x10, 0xc6, 0x55, 0x57, 0xbb, 0xdc, 0x25, 0x5b,
	0x8b, 0xe0, 0x19, 0xd7, 0x6e, 0xbb, 0x6b, 0x21, 0x33, 0xa1, 0x83, 0xef, 0x80, 0x5c, 0x96, 0xd8,
	0x80, 0x19, 0xab, 0x6a, 0x55, 0x63, 0xa7, 0x93, 0x39, 0xbf, 0xc1, 0xbd, 0x7c, 0x10, 0x35, 0x26,
	0x1f, 0x40, 0xb4, 0x98, 0x5f, 0xbe, 0xde, 0xac, 0x97, 0x75, 0x28, 0xe3, 0xc5, 0xdc, 0x63, 0xf2,
	0x35, 0xec, 0x2f, 0xe6, 0x97, 0x33, 0xa6, 0xb3, 0xcb, 0x33, 0xad, 0xa4, 0x0d, 0x37, 0xd5, 0xe1,
	0x14, 0xaf, 0xdd, 0xe9, 0x5c, 0xf1, 0xcd, 0x5a, 0x48, 0x7b, 0x61, 0x95, 0x16, 0x34, 0x5e, 0xcc,
	0x1d, 0x13, 0x89, 0xe4, 0x39, 0x4c, 0x2a, 0xcb, 0x17, 0x8c, 0xdf, 0x84, 0x3b, 0xeb, 0x7e, 0x43,
	0xf0, 0x86, 0x8e, 0xd7, 0xb6, 0x7b, 0xa9, 0x8a, 0x2c, 0x5c, 0x5e, 0x3b, 0xed, 0x1c, 0x8f, 0x9c,
	0x42, 0x54, 0x32, 0x63, 0x7c, 0x94, 0xd1, 0x0e, 0xa3, 0x86, 0x46, 0x9e, 0x43, 0xec, 0x80, 0xbb,
	0x10, 0x84, 0xb4, 0xd8, 0xd7, 0xff, 0x9a, 0x5b, 0x8b, 0x48, 0x9e, 0xc2, 0xd8, 0x41, 0x8c, 0x2f,
	0xde, 0x61, 0x54, 0xb3, 0xc8, 0x19, 0xbc, 0x97, 0xe9, 0xfc, 0x5d, 0x2e, 0xaf, 0x5f, 0xe5, 0x5c,
	0x48, 0x23, 0x7c, 0x9c, 0x93, 0x1d, 0xc6, 0xf7, 0x19, 0x90, 0xef, 0xe1, 0x51, 0x57, 0x5c, 0xc5,
	0xbe, 0xbf, 0x63, 0xa7, 0xfb, 0x4d, 0xc8, 0x1c, 0x48, 0x57, 0x81, 0xf9, 0x1c, 0xec, 0xd8, 0xe8,
	0x1e, 0x7e, 0xfa, 0x33, 0xec, 0x85, 0x0b, 0xd5, 0x35, 0x74, 0xb9, 0x52, 0xb2, 0x6a, 0x57, 0x0f,
	0x5c, 0x0f, 0xaf, 0x59, 0x5e, 0x84, 0x6e, 0xc5, 0xb5, 0xeb, 0xe1, 0x5b, 0xc1, 0x57, 0xcc, 0x56,
	0x47, 0xc5, 0x23, 0x37, 0x91, 0xcf, 0xcf, 0x43, 0x87, 0xf6, 0xcf, 0xcf, 0xd3, 0x3f, 0x7a, 0x10,
	0xd5, 0xe3, 0x93, 0x7c, 0x09, 0x71, 0x21, 0xae, 0x59, 0xf1, 0xd6, 0xb7, 0x7f, 0xaf, 0x33, 0x92,
	0x5f, 0x35, 0x1a, 0xda, 0xa6, 0x91, 0x6f, 0xe0, 0x80, 0xeb, 0x6d, 0x69, 0xd5, 0x6c, 0xa3, 0xdd,
	0x20, 0xdd, 0x62, 0x24, 0xcd, 0xf8, 0x9c, 0x75, 0x94, 0xf4, 0x0e, 0x99, 0x4c, 0x21, 0xc6, 0x52,
	0xfc, 0x80, 0x2f, 0x0c, 0x8c, 0x37, 0x3e, 0x9d, 0x04, 0xdb, 0x6f, 0x9d, 0x86, 0xb6, 0x09, 0xe9,
	0x4f, 0x10, 0xb7, 0x42, 0x21, 0x29, 0x4c, 0x98, 0x94, 0x1b, 0x37, 0x97, 0xb8, 0x0a, 0x27, 0x79,
	0x40, 0x3b, 0x32, 0x3f, 0x0e, 0x1c, 0x9e, 0x29, 0x69, 0x36, 0x6b, 0x3f, 0x4f, 0x06, 0xb4, 0x2b,
	0x4c, 0x1f, 0xc2, 0x41, 0x37, 0xd4, 0x74, 0x0f, 0x86, 0x18, 0x40, 0xfa, 0x67, 0x0f, 0xa0, 0x79,
	0x34, 0xb8, 0x11, 0xbb, 0x90, 0x56, 0x68, 0x61, 0xac, 0x49, 0x7a, 0x9d, 0x11, 0x5b, 0xcb, 0x69,
	0x43, 0x21, 0x0b, 0x20, 0xdc, 0x3b, 0xd1, 0xcd, 0x2e, 0x61, 0x9a, 0xbf, 0xdf, 0x0c, 0xcd, 0x3b,
	0x04, 0x7a, 0x8f, 0x91, 0x73, 0x6d, 0x4a, 0x21, 0xb3, 0xb7, 0xf9, 0x5a, 0xdc, 0x99, 0xee, 0x17,
	0x95, 0x9c, 0x36, 0x94, 0xf4, 0xab, 0x56, 0xa8, 0xae, 0x7f, 0x56, 0x6a, 0xb9, 0xac, 0x06, 0xae,
	0x07, 0x78, 0xfd, 0x72, 0xa5, 0xab, 0x29, 0xeb, 0x41, 0x7a, 0x08, 0xe4, 0x9f, 0x21, 0xa5, 0x31,
	0x44, 0xb5, 0x1b, 0x57, 0xb0, 0xee, 0xd3, 0x28, 0x1d, 0xc3, 0xc8, 0xbf, 0x7e, 0x96, 0x23, 0x7c,
	0x29, 0x3e, 0xfb, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xd6, 0xcd, 0xaf, 0x68, 0x0a, 0x00, 0x00,
}
