// Code generated by protoc-gen-go. DO NOT EDIT.
// source: action/ato_transaction.proto

package action

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ATO 认购交易对象
type AtoTransaction struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId            string   `protobuf:"bytes,4,opt,name=projectId,proto3" json:"projectId,omitempty"`
	PurchaserId          string   `protobuf:"bytes,5,opt,name=purchaserId,proto3" json:"purchaserId,omitempty"`
	PayValueOrder        int64    `protobuf:"varint,6,opt,name=payValueOrder,proto3" json:"payValueOrder,omitempty"`
	PayCryptocurrency    int32    `protobuf:"varint,7,opt,name=payCryptocurrency,proto3" json:"payCryptocurrency,omitempty"`
	PayValueReceive      int64    `protobuf:"varint,8,opt,name=payValueReceive,proto3" json:"payValueReceive,omitempty"`
	ExRate               float32  `protobuf:"fixed32,9,opt,name=exRate,proto3" json:"exRate,omitempty"`
	AtoAmount            int64    `protobuf:"varint,10,opt,name=AtoAmount,proto3" json:"AtoAmount,omitempty"`
	AtoAmountFinal       int64    `protobuf:"varint,11,opt,name=AtoAmountFinal,proto3" json:"AtoAmountFinal,omitempty"`
	OrderTime            int64    `protobuf:"varint,12,opt,name=orderTime,proto3" json:"orderTime,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,13,opt,name=receiveTime,proto3" json:"receiveTime,omitempty"`
	TokenTransferTime    int64    `protobuf:"varint,14,opt,name=tokenTransferTime,proto3" json:"tokenTransferTime,omitempty"`
	TokenTransferHash    string   `protobuf:"bytes,15,opt,name=tokenTransferHash,proto3" json:"tokenTransferHash,omitempty"`
	OrderStatus          int32    `protobuf:"varint,16,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AtoTransaction) Reset()         { *m = AtoTransaction{} }
func (m *AtoTransaction) String() string { return proto.CompactTextString(m) }
func (*AtoTransaction) ProtoMessage()    {}
func (*AtoTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6eb8b214583ef35, []int{0}
}

func (m *AtoTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtoTransaction.Unmarshal(m, b)
}
func (m *AtoTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtoTransaction.Marshal(b, m, deterministic)
}
func (m *AtoTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtoTransaction.Merge(m, src)
}
func (m *AtoTransaction) XXX_Size() int {
	return xxx_messageInfo_AtoTransaction.Size(m)
}
func (m *AtoTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_AtoTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_AtoTransaction proto.InternalMessageInfo

func (m *AtoTransaction) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AtoTransaction) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AtoTransaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AtoTransaction) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AtoTransaction) GetPurchaserId() string {
	if m != nil {
		return m.PurchaserId
	}
	return ""
}

func (m *AtoTransaction) GetPayValueOrder() int64 {
	if m != nil {
		return m.PayValueOrder
	}
	return 0
}

func (m *AtoTransaction) GetPayCryptocurrency() int32 {
	if m != nil {
		return m.PayCryptocurrency
	}
	return 0
}

func (m *AtoTransaction) GetPayValueReceive() int64 {
	if m != nil {
		return m.PayValueReceive
	}
	return 0
}

func (m *AtoTransaction) GetExRate() float32 {
	if m != nil {
		return m.ExRate
	}
	return 0
}

func (m *AtoTransaction) GetAtoAmount() int64 {
	if m != nil {
		return m.AtoAmount
	}
	return 0
}

func (m *AtoTransaction) GetAtoAmountFinal() int64 {
	if m != nil {
		return m.AtoAmountFinal
	}
	return 0
}

func (m *AtoTransaction) GetOrderTime() int64 {
	if m != nil {
		return m.OrderTime
	}
	return 0
}

func (m *AtoTransaction) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func (m *AtoTransaction) GetTokenTransferTime() int64 {
	if m != nil {
		return m.TokenTransferTime
	}
	return 0
}

func (m *AtoTransaction) GetTokenTransferHash() string {
	if m != nil {
		return m.TokenTransferHash
	}
	return ""
}

func (m *AtoTransaction) GetOrderStatus() int32 {
	if m != nil {
		return m.OrderStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*AtoTransaction)(nil), "action.AtoTransaction")
}

func init() { proto.RegisterFile("action/ato_transaction.proto", fileDescriptor_b6eb8b214583ef35) }

var fileDescriptor_b6eb8b214583ef35 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x49, 0xda, 0xe6, 0xff, 0xef, 0xd6, 0xb6, 0xba, 0x88, 0xcc, 0xa1, 0x87, 0x20, 0x22,
	0x39, 0x88, 0x1e, 0xfc, 0x04, 0x45, 0x10, 0x7b, 0x12, 0x62, 0xf1, 0x2a, 0x6b, 0x32, 0xd2, 0x68,
	0xbb, 0xbb, 0x6c, 0x26, 0x6a, 0xbe, 0x8f, 0x1f, 0x54, 0x32, 0x5b, 0x6d, 0x6c, 0x6e, 0x79, 0xbf,
	0xf7, 0x76, 0x32, 0xfb, 0x12, 0x31, 0x53, 0x19, 0x15, 0x46, 0x5f, 0x29, 0x32, 0x4f, 0xe4, 0x94,
	0x2e, 0xbd, 0xbe, 0xb4, 0xce, 0x90, 0x91, 0x91, 0x57, 0xa7, 0x5f, 0x7d, 0x31, 0x99, 0x93, 0x59,
	0xee, 0x02, 0xf2, 0x58, 0x0c, 0xcc, 0x87, 0x46, 0x07, 0x41, 0x1c, 0x24, 0xc3, 0xd4, 0x0b, 0x29,
	0x45, 0x9f, 0x6a, 0x8b, 0x10, 0xc6, 0x41, 0x32, 0x48, 0xf9, 0x59, 0x4e, 0x44, 0x58, 0xe4, 0xd0,
	0xe3, 0x58, 0x58, 0xe4, 0x72, 0x26, 0x86, 0xd6, 0x99, 0x57, 0xcc, 0x68, 0x91, 0x43, 0x9f, 0xf1,
	0x0e, 0xc8, 0x58, 0x8c, 0x6c, 0xe5, 0xb2, 0x95, 0x2a, 0xd1, 0x2d, 0x72, 0x18, 0xb0, 0xdf, 0x46,
	0xf2, 0x4c, 0x8c, 0xad, 0xaa, 0x1f, 0xd5, 0xba, 0xc2, 0x7b, 0x97, 0xa3, 0x83, 0x28, 0x0e, 0x92,
	0x5e, 0xfa, 0x17, 0xca, 0x0b, 0x71, 0x64, 0x55, 0x7d, 0xe3, 0x6a, 0x4b, 0x26, 0xab, 0x9c, 0x43,
	0x9d, 0xd5, 0xf0, 0x8f, 0xd7, 0xea, 0x1a, 0x32, 0x11, 0xd3, 0x9f, 0xe3, 0x29, 0x66, 0x58, 0xbc,
	0x23, 0xfc, 0xe7, 0xa9, 0xfb, 0x58, 0x9e, 0x88, 0x08, 0x3f, 0x53, 0x45, 0x08, 0xc3, 0x38, 0x48,
	0xc2, 0x74, 0xab, 0x9a, 0x5b, 0xcd, 0xc9, 0xcc, 0x37, 0xa6, 0xd2, 0x04, 0x82, 0xcf, 0xee, 0x80,
	0x3c, 0xe7, 0xfe, 0xbc, 0xb8, 0x2d, 0xb4, 0x5a, 0xc3, 0x88, 0x23, 0x7b, 0xb4, 0x99, 0x62, 0x9a,
	0xf5, 0x97, 0xc5, 0x06, 0xe1, 0xc0, 0x4f, 0xf9, 0x05, 0x4d, 0x37, 0xce, 0xaf, 0xc1, 0xfe, 0x98,
	0xfd, 0x36, 0x6a, 0x6e, 0x4d, 0xe6, 0x0d, 0x35, 0x7f, 0xa9, 0x97, 0xed, 0x9c, 0x09, 0xe7, 0xba,
	0x46, 0x27, 0x7d, 0xa7, 0xca, 0x15, 0x4c, 0xb9, 0xf1, 0xae, 0xd1, 0xbc, 0x9d, 0x57, 0x79, 0x20,
	0x45, 0x55, 0x09, 0x87, 0xdc, 0x65, 0x1b, 0x3d, 0x47, 0xfc, 0xd7, 0x5c, 0x7f, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x11, 0x21, 0xcc, 0x3c, 0x55, 0x02, 0x00, 0x00,
}
